# The top level compose file represents a set of IOCs that would be deployed
# to a given IOC server
#
# For this example we have a single compose file. However, if you wanted to keep
# all IOCs for a beamline in a single repo but deploy to multiple servers,
# then each server would have its own named compose file

# to deploy IOCs to the local machine, clone this repo and run the following
# command from the repo root:
#  docker compose --profile deploy up --detach
# or for a multiple server repo:
#  docker compose --profile deploy -f my_server_01.yml up --detach

# to deploy the IOCs to a workstation for testing and development, use:
# docker compose up --detach

include:
  - services/MOTOR_docker_image/compose.yml
  - services/PE_docker_image/compose.yml
  - services/gateway/compose.yml
  - services/pvagw/compose.yml

  # deploy profile only
  - services/epics-opis/compose.yml

services:
  init:
    image: ubuntu:latest
    security_opt:
      - label=disable
    restart: no
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: /bin/bash -c "/workspace/include/init.sh"
    environment:
      - DISPLAY=host.docker.internal:0
      - EPICS_CA_SERVER_PORT
      - EPICS_CA_REPEATER_PORT
      - EPICS_PVA_SERVER_PORT
      - CA_SUBNET
      - CA_BROADCAST
      - EPICS_PVA_NAME_SERVERS
      - EPICS_CA_NAME_SERVERS
      - EPICS_CA_ADDR_LIST