# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.6.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"
description: Example simulated camera for ophyd adsim

entities:
  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADSimDetector.simDetector
    PORT: cam
    P: "XF:31IDA-BI{Cam:Tbl}" 
    R: ":cam1:" 
    DATATYPE: 0
    WIDTH: 1024
    HEIGHT: 1024

  - type: ADCore.NDROI
    PORT: ROI1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":ROI1:"
    NDARRAY_PORT: cam

  - type: ADCore.NDROI
    PORT: ROI2
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":ROI2:"
    NDARRAY_PORT: cam

  - type: ADCore.NDROI
    PORT: ROI3
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":ROI3:"
    NDARRAY_PORT: cam

  - type: ADCore.NDROI
    PORT: ROI4
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":ROI4:"
    NDARRAY_PORT: cam

  - type: ADCore.NDProcess
    PORT: Proc1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Proc1:"
    NDARRAY_PORT: cam

  - type: ADCore.NDPvaPlugin
    PORT: PVA
    PVNAME: XF:31IDA-BI{Cam:Tbl}:PVA:OUTPUT
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":PVA:"
    NDARRAY_PORT: cam

  - type: ADCore.NDStdArrays
    PORT: image1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":image1:"
    NDARRAY_PORT: cam
    TYPE: Int8
    NELEMENTS: 1048576
    FTVL: CHAR

  - type: ADCore.NDStats
    PORT: Stats1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Stats1:"
    NDARRAY_PORT: Stats1
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats2
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Stats2:"
    NDARRAY_PORT: cam
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20
  
  - type: ADCore.NDStats
    PORT: Stats3
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Stats3:"
    NDARRAY_PORT: cam
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats4
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Stats4:"
    NDARRAY_PORT: cam
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDStats
    PORT: Stats5
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Stats5:"
    NDARRAY_PORT: cam
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDFileHDF5
    PORT: HDF1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":HDF1:"
    NDARRAY_PORT: cam

  - type: ADCore.NDFileTIFF
    PORT: TIFF1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":TIFF1:"
    NDARRAY_PORT: cam

  - type: ADCore.NDColorConvert
    PORT: CC1
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":CC1:"
    NDARRAY_PORT: cam
    ENABLED: 1
    TIMEOUT: 5.0

  - type: ADCore.NDOverlay
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Over1:"
    PORT: Over1
    NDARRAY_PORT: cam

  - type: ADCore.NDTransform
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":Trans1:"
    PORT: EnableCallbacks_RBV
    NDARRAY_PORT: cam

  - type: ADCore.NDTransform
    P: XF:31IDA-BI{Cam:Tbl}
    R: ":netCDF1:"
    PORT: EnableCallbacks_RBV
    NDARRAY_PORT: cam