# yaml-language-server: $schema=https://github.com/epics-containers/ioc-motorsim/releases/download/2024.9.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: REPLACE WITH DESCRIPTION

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: motorSim.simMotorController
    controllerName: sim-controller1
    numAxes: 3
    P: "XF:31IDA-OP{Tbl-Ax:"

  - type: motorSim.simMotorAxis
    controller: sim-controller1
    ADDR: 1
    M: X1}Mtr
    DESC: Motor Ax 1
    home: 1

  - type: motorSim.simMotorAxis
    controller: sim-controller1
    ADDR: 2
    M: X2}Mtr
    DESC: Motor Ax 2
    home: 2

  - type: motorSim.simMotorAxis
    controller: sim-controller1
    ADDR: 3
    M: X3}Mtr
    DESC: Motor Ax 3
    home: 3

  # - type: motorSim.simMotorAxis
  #   controller: sim-controller1
  #   ADDR: 4
  #   M: X4}Mtr
  #   DESC: Motor Ax 4
  #   home: 4

  # - type: motorSim.simMotorAxis
  #   controller: sim-controller1
  #   ADDR: 5
  #   M: X5}Mtr
  #   DESC: Motor Ax 5
  #   home: 5

  # - type: motorSim.simMotorAxis
  #   controller: sim-controller1
  #   ADDR: 6
  #   M: X6}Mtr
  #   DESC: Motor Ax 6
  #   home: 6
